name: Create Release and Build Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-and-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: |
          TAG=$(git tag --list | sort -V | tail -n 1)
          if [ -z "$TAG" ]; then
            echo "No tags found. Setting default tag to v0.1.0"
            TAG="v0.1.0"
          fi
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          NEW_TAG=$(cat VERSION)
          echo "New tag is $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a $NEW_TAG -m "Release $NEW_TAG"
          git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}
          git push origin $NEW_TAG

      - name: Debug NEW_TAG
        run: |
          echo "The new tag is $NEW_TAG"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          release_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image with tag
        run: |
          TAG=${{ steps.tag_version.outputs.NEW_TAG }}
          docker build -t naotokubota/tosa:$TAG -t naotokubota/tosa:latest -f docker/Dockerfile .
          docker push naotokubota/tosa:$TAG
          docker push naotokubota/tosa:latest
