name: Update Version

on:
  push:
    branches:
      - develop
    paths:
      - 'VERSION'

jobs:
  update-readme-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for merge commit
        id: check_merge
        run: |
            if [ "$(git rev-list --count HEAD^@)" -gt 1 ]; then
            echo "This is a merge commit. Skipping workflow."
            exit 0
            fi

      - name: Read version from VERSION file
        id: read_version
        run: |
          NEW_VERSION=$(cat VERSION)
          echo "New version is $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Get the branch name
        id: get_branch
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"

      - name: Update README.md with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/# Tosa (v[0-9]*\.[0-9]*\.[0-9]*)/# Tosa (${NEW_VERSION})/" README.md

      - name: Update Tosa with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          NEW_VERSION=${NEW_VERSION#v}
          sed -i "s/\"[0-9]*\.[0-9]*\.[0-9]*\"/\"${NEW_VERSION}\"/" src/main.rs

      - name: Update Dockerfile with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/${NEW_VERSION}/" docker/Dockerfile

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md src/main.rs docker/Dockerfile
          git commit -m "actions: Ready for ${{ steps.read_version.outputs.NEW_VERSION }}"
          git push origin HEAD:${{ steps.get_branch.outputs.BRANCH_NAME }}
